### ISSUE TITLE
Getting Error: invalid gist id: undefined

### ISSUE THREAD

**Issue by ff6347** [mbostock/gistup#11]
When trying to use the module (v 0.0.10) I get this error:  

```
/usr/local/lib/node_modules/gistup/bin/gistup:85
    throw error;
          ^
Error: invalid gist id: undefined
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/gistup/bin/gistup:248:69)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)  
```

How can I fix this?

**Comment by Seondong** [comment]
Thank god, I had the same issue, I didn't know that how to access the home directory. 
The home directory can be accessible by  cd ~/    instead of going all the way up to the root directory
By making .gistup file(with my personal token) in ~/ directory, it works like a charm.
Thanks!!
---
For someone who doesn't work,
You can make a gist from github webpage and 'git clone' and push again.
