### ISSUE TITLE
README doesn't explain how to not add files to your repo

### ISSUE THREAD

**Issue by hdon** [mbostock/gistup#34]
I made my repo first and then used gistup, but it added other files to my repo, and then made a commit, before posting a gist.

It was intuitive to me that if I had an existing git repo, it wouldn't add any files to my repo.

If there is an option for not adding any files, it's not in the README :(

**Comment by mbostock** [comment]
Three ways to do this are (indirectly) described in the README:

1. Use `gistup -i` to confirm each untracked file interactively.

2. Specify the files you wish to add explicitly as `gistup -- file1 file2`, rather than the default behavior of adding untracked files. If you specify a file that you’ve previously added and committed to the git repository, the initial gistup commit should be empty.

3. Use `gistup -x '*'` to ignore untracked files in the current directory. (Gistup already ignores untracked files in subdirectories because Gists aren’t supposed to have subdirectories.)
